sudo: true
dist: xenial
language: cpp
compiler: gcc

env:
  - secure: "r37WzFlT/Rnl24SuPzflKeSV3Fm5xxlpB5YOzBhKj5QzhG7+/4qw3Jg2LtaNaCD0gYfwX6SYDS46bngpvW6Qbg2OvmUYEnmJ2Z14bbPijNVQk1pUmvd9NUXC8AT5QKON1bO+WhqQ5l2W28L1W3bhkazUSIqTFBk49YziCuDchIM9N0fj4PgL7l/k6MOsa2fVNN9R6HUhy0/AZvkNWxLXBt+buap3iGfAVjh/fXgDq0KplKQ5wKGYaPSwYN6PhLzQWNLTQySUO9a8RBwnur+Pk4m0efn91ZbLC8+wk6gWAHwh92/XIuwm2Pm3TxA/bduRMgloUn7dyIsN5HRe2lAvRfjvKupxKQqaL1lpz/Za0Or3tc8XWevNLxftctrVsRArmdKMay2IYVfGxFIBv8aCz7VETlb6MKGewq9m3DQT8+xN7Px3NZN27g2jemPBMzboxyqoMf7BDbNZAK4soz+LIYgKrdCJJaHOxhfyTuBroe7nYNAmW9tqHnGQye+lmAgdk8svGjRFEEDK76ulmkNrQLgux3abghvpA2lweaK5dTNJEuES13VrHbWasDf5qFAwEYuC3HIUcE3yCH6nx05BGiqHBD+dMJmjDg2aFtYCkSGzV3BeZF5l1m17hsFr0Gl3REs+FT8Uw80YAP66s7EuPteXBHZ8l1czbF+qdigdt1k="

matrix:
  fast_finish: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

# Handle git submodules yourself
git:
  submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  #  installation coveralls used to send gcov to coveralls.io
  - pip install --user cpp-coveralls

install:
  # install flex 2.6.4
  - wget https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz
  - tar -xzvf flex-2.6.4.tar.gz
  - pushd flex-2.6.4 && ./configure --prefix=/usr && make && sudo make install && popd
  # install bison 3.2
  - wget https://ftp.gnu.org/gnu/bison/bison-3.2.tar.gz
  - tar -xzvf bison-3.2.tar.gz
  - pushd bison-3.2 && ./configure --prefix=/usr && make && sudo make install && popd

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - export GCOV=gcov-7
  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  - sudo ln -s /usr/bin/gcov-7 /usr/local/bin/gcov
  - flex --version && bison --version
  - g++ -v && cmake --version
  - gcov -v
  # generate flex-bison
  - make -C src/parser/flex-bison
  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build
  # run cmake; here we assume that the project's top-level CMakeLists.txt is located at '..'
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DOPTION_BUILD_TESTS=OFF -DTARGET_CPU=$TARGET_CPU -DCOVERALLS=ON
  - cmake --build .
  # execute tests_run
  - ./bin/tests_run [implemented]

after_success:
  - ls
  #  - coveralls -h
  - echo $GITHUB_SECRET_TOKEN
  - cd ..
  - |
    coveralls --build-root build --gcov gcov-7 --gcov-options '\-lp' \
     -e build/src/lib \
     -e build/CMakeFiles \
     -e build/CMakeFiles/feature_tests.c \
     -e build/CMakeFiles/feature_tests.cxx \
     -e src/lib \
     -e src/include \
     -e tests
     -E ".*CMakeFiles.*" \
     -E ".*lib.*"